#server:
#  port: 4444
#spring:
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    name: ashu
#    password: WHfcwayTSjcyqjzEEEzLdOTNJpswQUke
#    url: jdbc:mysql://root:WHfcwayTSjcyqjzEEEzLdOTNJpswQUke@mysql.railway.internal:3306/railway
#    username: root
#  jpa:
#    hibernate:
#      ddl-auto: update
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
#  main:
#    allow-circular-references: true
#  servlet:
#    multipart:
#      max-file-size: '10MB '
#      max-request-size: 10MB
